---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - На сайте должна быть добавлена возможность оплаты
  - При оформлении заказа пользователь должен оставлять свои контактные данные
  - Сайт должен соответсвовать Законодальству РФ:152-ФЗ «О персональных данных». 
  - У сайта должна быть возможность управления от имени Администратора для редактирования категорий,товаров,цен
  - У сайта должна быть информация с контактами продавца - телефон,почта 
  - У сайта должна стоять по умолчанию языковая локализация, ориентированна на основного покупателя
  - Цены на товары должны быть в валюте, удобной основному пользователю
